language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"

os:
 - linux
 - windows

sudo: enabled
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3-cairo ; fi

install:
  - pip install -r requirements.txt

script: python tests.py
